ARG app_port
FROM node:12-alpine as builder
RUN npm install -g typescript
RUN rm -rf /app/server
RUN mkdir -p /app/server
WORKDIR /app/server
COPY . /app/server
RUN npm run-script build

FROM node:12-alpine

WORKDIR /app/server
COPY --from=
builder /app/server/package.json ./package.json
COPY --from=builder /app/server/node_modules node_modules
COPY --from=builder /app/server/base-packages base-packages
COPY --from=builder /app/server/logs logs
COPY --from=builder /app/server/dist dist
COPY --from=builder /app/server/swagger.json ./swagger.json
COPY --from=builder /app/server/.env ./.env

EXPOSE $app_port
EXPOSE $debug_port
CMD [ "npm", "start" ]
